### PR TITLE
tests for `help`, `log`, `clean`

### PR DESCRIPTION
**Pull request by AABur**
RE: #232 

Tests for `help`, `log`, `clean`

### CODE REVIEW

**Comment by PawelLipski** [comment]
Huh still no status reported from CircleCI 🤔 lemme open a ticket against their support

**Comment by PawelLipski** [comment]
AFAICS https://app.circleci.com/pipelines/github/AABur/git-machete is still there... you've pressed `Stop building` in `Project Settings -> Overview` right?

(TBH I'm not aware if there's any other way of "deactivating" a project in CircleCI tho)

**Comment by AABur** [comment]
> AFAICS [app.circleci.com/pipelines/github/AABur/git-machete](https://app.circleci.com/pipelines/github/AABur/git-machete) is still there... you've pressed `Stop building` in `Project Settings -> Overview` right?
> 
> (TBH I'm not aware if there's any other way of "deactivating" a project in CircleCI tho)

I did this after that PR. When I saw that CircleCi was not running for my PR. I didn't immediately find out how to turn it off.

**Comment by PawelLipski** [comment]
Opened a support ticket, let's see what happens... they were quick to respond recently :)

**Comment by PawelLipski** [comment]
If you could rebase your PR stack onto the recent develop... `git machete traverse` recognizes squash merges since recently  as well :)

**Comment by PawelLipski** [comment]
Wow, CircleCI is back... did you change anything @AABur? or did _automagically_ sort itself out?

**Comment by PawelLipski** [comment]
Btw, in retrospect, the decision to include Codecov was a good one, props for that... makes merging such PRs much easier as I see that fundamentally nothing changed

**Review by PawelLipski — APPROVED** [review]

**Comment by AABur** [comment]
> Wow, CircleCI is back... did you change anything @AABur? or did _automagically_ sort itself out?

I figured out how to properly disable CircleCI

**Comment by PawelLipski** [comment]
For the record, what was the trick?

**Comment by AABur** [comment]
> For the record, what was the trick?

[How to stop building by manually removing the CircleCI webhook and deploy key from your GitHub repository](https://support.circleci.com/hc/en-us/articles/360021666393-How-to-stop-building-by-manually-removing-the-CircleCI-webhook-and-deploy-key-from-your-GitHub-repository)

**Pull request merged**
