### PR TITLE
Stop bumping Homebrew formula

### LINKED ISSUE #1254: Stop bumping Homebrew formula
This should be handled by BrewTestBot now that git-machete has been added to [`.github/autobump.txt` in `Homebrew/homebrew-core`](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt) on [PR #171225 to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/171225/files#diff-895127b46978b016c724afe1fe53341d3d25253eead3b82d796b9bd72aa0c9a9R840).

Let's still check if these updates are correctly performed (preferably, soon after v3.25.3/v3.26.0 release).

### PR DESCRIPTION
**Pull request by PawelLipski**

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm curious. How does it work then? @PawelLipski 

I mean they (homebrew) are checking on their own

**Comment by ccoVeille** [comment]
Found my reply there obviously…

https://github.com/VirtusLab/git-machete/issues/1254#issue-2308819663

**Comment by PawelLipski** [comment]
Yeah, it looks that it works... automagically somehow 😅 as for many other packaging systems (see [PACKAGES.md](https://github.com/VirtusLab/git-machete/blob/develop/PACKAGES.md) -> _Released by_ column).

Btw you're an avid follower of this project, I didn't expect such an internal issue to spur any responses 😅

**Comment by ccoVeille** [comment]
> Yeah, it looks that it works... automagically somehow 😅 as for many other packaging systems (see [PACKAGES.md](https://github.com/VirtusLab/git-machete/blob/develop/PACKAGES.md) -> _Released by_ column).
> 
> Btw you're an avid follower of this project, I didn't expect such an internal issue to spur any responses 😅 

In fact, I'm interested by your project and many other golang projects.

I'm also using and promoting using homebrew for packaging go binary like yours. It allows to be informed of a new version, and upgrades easily.

I recently suggesting this approach on a few project. I suggested using local tap as it's easy to maintain via GoReleaser.

I didn't check (yet) how to add a package to official homebrew. So I was interested by the code you changed, that appeared to be quite complicated. So I was asking how it could work automagically without it. I will have a look at autobump.

**Comment by PawelLipski** [comment]
> go binary like yours

Hmmm pls note that this is by no means a golang project 😅 pure python 3, no binary code at all 

> So I was asking how it could work automagically without it. I will have a look at autobump.

Autobump looks like a good choice. We used to have a quite painful process that used `brew bump-formula-pr`. See [ci/homebrew/ci-deploy.sh](https://github.com/VirtusLab/git-machete/blob/v3.25.2/ci/homebrew/ci-deploy.sh) and esp. [history of this file](https://github.com/VirtusLab/git-machete/commits/v3.25.2/ci/homebrew/ci-deploy.sh) for how many things needed to be changed as we discovered new corner cases and homebrew(-core) introduced breaking changes.

**Comment by ccoVeille** [comment]
> > go binary like yours
> 
> Hmmm pls note that this is by no means a golang project 😅 pure python 3, no binary code at all 

Lol. I'm so ridiculous 🤣😅 I cannot stop laughing.

I'm a gopher, I'm sorry if I commented the wrong way. Muscle memory on my phone.

> > So I was asking how it could work automagically without it. I will have a look at autobump.
> 
> Autobump looks like a good choice. We used to have a quite painful process that used `brew bump-formula-pr`. See [ci/homebrew/ci-deploy.sh](https://github.com/VirtusLab/git-machete/blob/v3.25.2/ci/homebrew/ci-deploy.sh) and esp. [history of this file](https://github.com/VirtusLab/git-machete/commits/v3.25.2/ci/homebrew/ci-deploy.sh) for how many things needed to be changed as we discovered new corner cases and homebrew(-core) introduced breaking changes).

Yes, I agree with you autobump is a way better process.

**Comment by PawelLipski** [comment]
Haha np 🇳🇵

**Pull request merged**
