### PR TITLE
Fixed GitHub Spelling

### LINKED ISSUE #454: Use consistent style: Github or GitHub (rather the latter)
GitHub styles itself... well, `GitHub` ;) let's use this capitalization across all docs/shell completion etc.

### PR DESCRIPTION
**Pull request by MahmoudHamdy02**
Fixed the spelling for Issue #454

### CODE REVIEW

**Comment by PawelLipski** [comment]
Hey there :) thanks for the contrib... if you could switch the base branch to `develop`! according to https://github.com/VirtusLab/git-machete/blob/master/CONTRIBUTING.md#faqs-about-pull-requests

**Comment by MahmoudHamdy02** [comment]
The base branch should be changed now!

**Comment by PawelLipski** [comment]
Ok! pls rebase onto the most recent develop now and I think we'll be ready to go

**Comment by PawelLipski** [comment]
Btw, out of curiosity... how did you learn of this project?

**Comment by MahmoudHamdy02** [comment]
I only see one develop branch, can you give me more details?

I'm new to open source so I searched for open issues on GitHub and tried to find some issues I could contribute to :)

**Comment by PawelLipski** [comment]
> I only see one develop branch, can you give me more details?

Just `git rebase develop` while your branch is checked out should be enough :) _most recent develop_ was a mental shortcut, I just meant _most recent commit pushed to develop branch_ (i.e. just make sure that you `git pull origin develop` before the rebase).

Alternatively, just use _Update branch_:

image

(select _Update with rebase_ from the dropdown)

but then you need to make sure that you have the commits rebased by GitHub reflected on your local machine :/

**Comment by MahmoudHamdy02** [comment]
I have tried to Update with rebase, please let me know if it is alright now.

**Review by PawelLipski — APPROVED** [review]

**Comment by PawelLipski** [comment]
Okay! merged :)

**Pull request merged**
