### PR TITLE
Tests for `github`

### PR DESCRIPTION
**Pull request by AABur**
RE: #232 

Tests for `github`

### CODE REVIEW

**Comment by PawelLipski** [comment]
Hmmm too many commits on this PR 🤔 pls limit to just [test github](https://github.com/VirtusLab/git-machete/pull/505/commits/2212348fd6da896a4eca965f53546d89fa2bdcdf)... some `git cherry-pick` might be a good choice

**Comment by PawelLipski** [comment]
Generally, to keep the work with many PRs managable, pls stick to linear (merge-commit-free) history, see https://slides.com/plipski/git-linear-history/

**Comment by AABur** [comment]
> Hmmm too many commits on this PR 🤔 pls limit to just [test github](https://github.com/VirtusLab/git-machete/pull/505/commits/2212348fd6da896a4eca965f53546d89fa2bdcdf)... some `git cherry-pick` might be a good choice

This happens because I don't wait for PRs to be merged, but make each next one from the previous one. This is easily solved by `rebase` immediately after the merging of the previous PR. This is easily done on GitHub. I'm keeping an eye on it.

**Comment by AABur** [comment]
> Generally, to keep the work with many PRs managable, pls stick to linear (merge-commit-free) history, see [slides.com/plipski/git-linear-history](https://slides.com/plipski/git-linear-history/)

Thank you. I'll keep that in mind for the future.

**Comment by PawelLipski** [comment]
> This happens because I don't wait for PRs to be merged, but make each next one from the previous one

Sure, that's exactly what git-machete promotes :) 

Just the one thing to avoid is **mixing true (2-parent) merges and squashes**. Other combinations work fine... typically I use just rebase (`git machete update`, `git machete traverse`) and fast-forward (`git machete advance`) :)

**Review by PawelLipski — APPROVED** [review]

**Pull request merged**
